apiVersion: "v1"
kind: "ReplicationController"
metadata:
  annotations:
    fabric8.io/git-branch: "master"
    fabric8.io/git-commit: "4af8baf9b5979d757030978aa4bfd619c6114ee0"
  labels:
    project: "hola-wildflyswarm"
    provider: "fabric8"
    version: "1.2"
    group: "org.hola.wildflyswarm"
  name: "hola-wildflyswarm"
spec:
  replicas: 1
  selector:
    project: "hola-wildflyswarm"
    provider: "fabric8"
    version: "1.2"
    group: "org.hola.wildflyswarm"
  template:
    metadata:
      annotations: {}
      labels:
        project: "hola-wildflyswarm"
        provider: "fabric8"
        version: "1.2"
        group: "org.hola.wildflyswarm"
    spec:
      containers:
      - args: []
        command: []
        env:
        - name: "AB_JOLOKIA_OFF"
          value: "true"
        - name: "GREETING_BACKEND_SERVICE_HOST"
          value: "hola-backend"
        - name: "GREETING_BACKEND_SERVICE_PORT"
          value: "80"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "weipeng2k/hola-wildflyswarm:1.2"
        name: "hola-wildflyswarm"
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 8778
          name: "jolokia"
        readinessProbe:
          httpGet:
            path: "/api/holaV1"
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 30
        securityContext: {}
        volumeMounts: []
      imagePullSecrets: []
      nodeSelector: {}
      volumes: []
