apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    project: "hola-wildflyswarm"
    provider: "fabric8"
    version: "1.3"
    group: "org.hola.wildflyswarm"
  name: "hola-wildflyswarm"
spec:
  deprecatedPublicIPs: []
  externalIPs: []
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "hola-wildflyswarm"
    provider: "fabric8"
    group: "org.hola.wildflyswarm"
  type: "LoadBalancer"

